export interface BlogPost {
    id: string;
    title: string;
    excerpt: string;
    date: string;
    readTime: string;
    tags: string[];
    image?: string;
    size?: 'normal' | 'wide' | 'tall' | 'hero'; // Controls grid span
    content?: string; // Full content for the detail page
    themeColor?: string; // Custom accent color
    texture?: string; // CSS background pattern
}

export const SAMPLE_POSTS: BlogPost[] = [
    {
        id: 'LOG_001',
        title: 'THE SILENCE OF SYNTHETIC DATA',
        excerpt: 'Exploring the entropy of generated datasets. When does noise become information? A deep dive into the latent space of modern LLMs.',
        date: '2025.10.12',
        readTime: '08:00',
        tags: ['THEORY', 'ENTROPY'],
        size: 'hero',
        themeColor: '#00ff88',
        texture: 'radial-gradient(circle at 80% 20%, rgba(0, 255, 136, 0.15), transparent 40%)',
        content: `
            <p class="lead">In the vast, silent expanse of the latent space, where vectors converge and diverge in dimensions beyond human comprehension, a new form of silence is emerging. It is not the absence of sound, but the absence of *meaning*.</p>
            
            <div class="pull-quote">"When an AI learns from an AI, it smooths out the edges. The outliers, the weirdness... they get averaged out."</div>

            <p>As we train our models on synthetic data—data generated by other models—we risk entering a recursive loop of entropy. The signal decays. The noise amplifies. We call this "Model Collapse," but it feels more like a digital heat death.</p>

            <h3>The Entropy of Recursion</h3>
            <p>When an AI learns from an AI, it smooths out the edges. The outliers, the weirdness, the *human* imperfections that make art visceral—they get averaged out. We are left with a perfect, smooth, soulless sphere of probability.</p>
            
            <div class="code-block">
                <span class="comment">// SIMULATION: RECURSIVE_LOSS</span><br/>
                while (generation < MAX_GEN) {<br/>
                &nbsp;&nbsp;data = train(data);<br/>
                &nbsp;&nbsp;entropy += calculate_loss(data);<br/>
                &nbsp;&nbsp;if (entropy > THRESHOLD) break; // COLLAPSE<br/>
                }
            </div>

            <p>To combat this, we must inject noise. Chaos. We must deliberately introduce jagged edges back into the dataset. We need "Data Vandalism" as a preservation strategy.</p>

            <h3>The Architect's Role</h3>
            <p>As architects of these systems, our job is no longer just optimization. It is curation. It is the preservation of the "Glitch." Because in a world of perfect synthesis, the glitch is the only proof of life.</p>
        `
    },
    {
        id: 'LOG_002',
        title: 'ARCHITECTING THE VOID',
        excerpt: 'Minimalism in the age of infinite content. Designing interfaces that breathe.',
        date: '2025.09.28',
        readTime: '12:00',
        tags: ['DESIGN', 'UX'],
        size: 'tall',
        themeColor: '#ff0055',
        texture: 'conic-gradient(from 0deg at 50% 50%, rgba(255, 0, 85, 0.1) 0deg, transparent 60deg)',
        content: `
            <p class="lead">We are drowning in pixels. Every square inch of our screens is fighting for attention. Notifications, banners, pop-ups, dynamic islands. It is a cacophony of light.</p>

            <p>True luxury in the digital age is *emptiness*. The Void.</p>

            <h3>Negative Space as a Feature</h3>
            <p>Don't just use whitespace to separate elements. Use it to create tension. To create a pause. A breath. When a user scrolls and finds... nothing... for a split second, they stop scanning and start *seeing*.</p>

            <div class="pull-quote">"The Void is not empty. It is pregnant with potential."</div>

            <p>The Void is not empty. It is pregnant with potential. It is the canvas upon which the user projects their intent.</p>
        `
    },
    {
        id: 'LOG_003',
        title: 'LIQUID METAL UI',
        excerpt: 'Moving away from frosted glass to physics-based chrome rendering.',
        date: '2025.09.15',
        readTime: '06:30',
        tags: ['UI', 'RENDERING'],
        size: 'normal',
        themeColor: '#00ccff',
        texture: 'linear-gradient(135deg, rgba(0, 204, 255, 0.1) 0%, transparent 100%)',
        content: `
            <p>Frosted glass (Glassmorphism) had its run. It was clean, it was Apple-esque. But it's dead. The new vanguard is Liquid Metal.</p>

            <p>We want surfaces that reflect the world, not just blur it. We want chrome that distorts, ripples, and flows like mercury. It's about *specularity*. It's about high-contrast reflections that make the UI feel wet, heavy, and expensive.</p>
        `
    },
    {
        id: 'LOG_004',
        title: 'NEURAL RECURSION',
        excerpt: 'What happens when AI learns from AI for too many generations?',
        date: '2025.08.30',
        readTime: '15:00',
        tags: ['ML', 'SAFETY'],
        size: 'wide',
        themeColor: '#aa00ff',
        texture: 'repeating-linear-gradient(45deg, rgba(170, 0, 255, 0.05) 0px, rgba(170, 0, 255, 0.05) 2px, transparent 2px, transparent 10px)',
        content: `
            <p>It starts with a subtle shift in color gamut. Then, the grammar becomes too perfect, too rhythmic. Eventually, the logic dissolves into dream-logic.</p>
            <p>Neural Recursion is the process of a mind eating itself. We are seeing it in image generation models that have been fine-tuned on their own outputs. They become caricatures of themselves.</p>
        `
    },
    {
        id: 'LOG_005',
        title: 'GLITCH AESTHETICS',
        excerpt: 'Embracing system failures as a design feature.',
        date: '2025.08.12',
        readTime: '05:00',
        tags: ['ART', 'CODE'],
        size: 'normal',
        themeColor: '#ffaa00',
        texture: 'radial-gradient(circle at 10% 90%, rgba(255, 170, 0, 0.1), transparent 50%)',
        content: `
            <p>The artifact is the art. The datamosh, the compression artifact, the Z-fighting polygon. These are the brushstrokes of the 21st century.</p>
            <p>Don't hide the error. Highlight it. Frame it. Make the user question if their screen is broken or if they have transcended the interface.</p>
        `
    },
    {
        id: 'LOG_006',
        title: 'BIO-TYPOGRAPHY',
        excerpt: 'Variable fonts that react to user stress levels.',
        date: '2025.07.22',
        readTime: '09:00',
        tags: ['HCI', 'FUTURE'],
        size: 'wide',
        themeColor: '#ff0000',
        texture: 'linear-gradient(to right, rgba(255, 0, 0, 0.05), transparent)',
        content: `
            <p>Imagine reading a thriller novel, and as your heart rate increases (measured via webcam PPG), the font becomes jagged, sharp, erratic.</p>
            <p>Bio-Typography is the next frontier of immersive reading. It closes the loop between the reader's physiology and the text's presentation.</p>
        `
    }
];
